name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output

      - uses: Platane/snk@v3
        with:
          github_user_name: erickwilson
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate github-contribution-grid-snake.svg"
          add: "github-contribution-grid-snake.svg"
